### ISSUE TITLE
$SCRIPTPATH needs double quotes

### ISSUE THREAD

**Issue by bmclean2** [AethanFoot/leftwm-theme-dracula-rounded#1]
I'm not sure why this hasn't been mentioned yet, but on my machine, every instance of the `$SCRIPTPATH` variable in the **up** and **down** files needs to be double-quoted because there is a space in the full path at "Dracula Rounded." I'm not a bash expert, but double quoting fixed the issue.

**Comment by AethanFoot** [comment]
Ye, without double quotes there are issue with string spitting. Will update this now

**Comment by bmclean2** [comment]
Great, thx.
