### ISSUE TITLE
Error in polybar (i think so)

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [AethanFoot/leftwm-theme-dracula-rounded#2]
You created a beautiful theme, but after installing it (via leftwm-themes) you got an error message in the polybar. I have absolutely no idea what to do except to report the error, the screenshot shows the error itself and confirmation that I have all the dependencies installed
![leftwm_dracula_theme_bugrepport](https://user-images.githubusercontent.com/46464602/114232349-65f1a480-9984-11eb-9df7-a53340399e2a.png)

EDIT: I figured out the cause of the error and have already created a PR

**Comment by AethanFoot** [comment]
Thank you, and thank you for fixing the issue.
